spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: examples-job
  cloud:
    consul:
      discovery:
        tags: ver=1.0, provider=nebula
server:
  port: 9060

nebula:
  elastic:
    namespace: examples-job
