spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: examples-consumer
  cloud:
    consul:
      discovery:
        tags: ver=1.0, provider=nebula
server:
  port: 9070
