spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: examples-account-ms
  cloud:
    consul:
      discovery:
        tags: ver=1.0, provider=nebula
server:
  port: 9070

nebula:
  seata:
    txServiceGroup: my_test_tx_group
    enabled: true
